// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: plugin_runtime.capnp

#include "rpp_cpp/plugin_runtime.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<52> b_a23e8c8b9e016532 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     50, 101,   1, 158, 139, 140,  62, 162,
     21,   0,   0,   0,   3,   0,   0,   0,
    213, 186, 173, 219, 186, 173, 219, 186,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  26,   1,   0,   0,
     37,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0, 199,   0,   0,   0,
    161,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  80, 108, 117,
    103, 105, 110,  82, 117, 110, 116, 105,
    109, 101,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     12,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21, 235, 158, 185,   6, 234,   7, 248,
    138,  98, 128, 193,  48, 133,  66, 251,
     81,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     69,   0,   0,   0,   7,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
    174,  55, 145,  46, 231,  87, 176, 243,
    237, 133, 198, 172, 121, 154, 127, 131,
     57,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     49,   0,   0,   0,   7,   0,   0,   0,
      2,   0,   0,   0,   0,   0,   0,   0,
    104, 148,  80,  53,  58, 123,  37, 222,
     94, 203,  23,  46, 227, 180, 140, 133,
     37,   0,   0,   0, 106,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
    112, 105, 110, 103,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    115, 104, 117, 116, 100, 111, 119, 110,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    108, 105, 115, 116,  65, 100,  97, 112,
    116, 101, 114, 115,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::capnp::word const* const bp_a23e8c8b9e016532 = b_a23e8c8b9e016532.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_a23e8c8b9e016532[] = {
  &s_837f9a79acc685ed,
  &s_858cb4e32e17cb5e,
  &s_de257b3a35509468,
  &s_f3b057e72e9137ae,
  &s_f807ea06b99eeb15,
  &s_fb428530c180628a,
};
static const uint16_t m_a23e8c8b9e016532[] = {2, 0, 1};
const ::capnp::_::RawSchema s_a23e8c8b9e016532 = {
  0xa23e8c8b9e016532, b_a23e8c8b9e016532.words, 52, d_a23e8c8b9e016532, m_a23e8c8b9e016532,
  6, 3, nullptr, nullptr, nullptr, { &s_a23e8c8b9e016532, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<18> b_f807ea06b99eeb15 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     21, 235, 158, 185,   6, 234,   7, 248,
     35,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 122,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  80, 108, 117,
    103, 105, 110,  82, 117, 110, 116, 105,
    109, 101,  46, 112, 105, 110, 103,  36,
     80,  97, 114,  97, 109, 115,   0,   0, }
};
::capnp::word const* const bp_f807ea06b99eeb15 = b_f807ea06b99eeb15.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_f807ea06b99eeb15 = {
  0xf807ea06b99eeb15, b_f807ea06b99eeb15.words, 18, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_f807ea06b99eeb15, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<18> b_fb428530c180628a = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    138,  98, 128, 193,  48, 133,  66, 251,
     35,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 130,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  80, 108, 117,
    103, 105, 110,  82, 117, 110, 116, 105,
    109, 101,  46, 112, 105, 110, 103,  36,
     82, 101, 115, 117, 108, 116, 115,   0, }
};
::capnp::word const* const bp_fb428530c180628a = b_fb428530c180628a.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_fb428530c180628a = {
  0xfb428530c180628a, b_fb428530c180628a.words, 18, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_fb428530c180628a, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<19> b_f3b057e72e9137ae = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    174,  55, 145,  46, 231,  87, 176, 243,
     35,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 154,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  80, 108, 117,
    103, 105, 110,  82, 117, 110, 116, 105,
    109, 101,  46, 115, 104, 117, 116, 100,
    111, 119, 110,  36,  80,  97, 114,  97,
    109, 115,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_f3b057e72e9137ae = b_f3b057e72e9137ae.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_f3b057e72e9137ae = {
  0xf3b057e72e9137ae, b_f3b057e72e9137ae.words, 19, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_f3b057e72e9137ae, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<19> b_837f9a79acc685ed = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    237, 133, 198, 172, 121, 154, 127, 131,
     35,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 162,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  80, 108, 117,
    103, 105, 110,  82, 117, 110, 116, 105,
    109, 101,  46, 115, 104, 117, 116, 100,
    111, 119, 110,  36,  82, 101, 115, 117,
    108, 116, 115,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_837f9a79acc685ed = b_837f9a79acc685ed.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_837f9a79acc685ed = {
  0x837f9a79acc685ed, b_837f9a79acc685ed.words, 19, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_837f9a79acc685ed, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<19> b_de257b3a35509468 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    104, 148,  80,  53,  58, 123,  37, 222,
     35,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 186,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  80, 108, 117,
    103, 105, 110,  82, 117, 110, 116, 105,
    109, 101,  46, 108, 105, 115, 116,  65,
    100,  97, 112, 116, 101, 114, 115,  36,
     80,  97, 114,  97, 109, 115,   0,   0, }
};
::capnp::word const* const bp_de257b3a35509468 = b_de257b3a35509468.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_de257b3a35509468 = {
  0xde257b3a35509468, b_de257b3a35509468.words, 19, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_de257b3a35509468, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<40> b_858cb4e32e17cb5e = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     94, 203,  23,  46, 227, 180, 140, 133,
     35,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 194,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  80, 108, 117,
    103, 105, 110,  82, 117, 110, 116, 105,
    109, 101,  46, 108, 105, 115, 116,  65,
    100,  97, 112, 116, 101, 114, 115,  36,
     82, 101, 115, 117, 108, 116, 115,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   1,   0,
     40,   0,   0,   0,   2,   0,   1,   0,
     97, 100,  97, 112, 116, 101, 114, 115,
      0,   0,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   3,   0,   1,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
     10, 102, 207, 203, 121, 161,  46, 165,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     14,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_858cb4e32e17cb5e = b_858cb4e32e17cb5e.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_858cb4e32e17cb5e[] = {
  &s_a52ea179cbcf660a,
};
static const uint16_t m_858cb4e32e17cb5e[] = {0};
static const uint16_t i_858cb4e32e17cb5e[] = {0};
const ::capnp::_::RawSchema s_858cb4e32e17cb5e = {
  0x858cb4e32e17cb5e, b_858cb4e32e17cb5e.words, 40, d_858cb4e32e17cb5e, m_858cb4e32e17cb5e,
  1, 1, i_858cb4e32e17cb5e, nullptr, nullptr, { &s_858cb4e32e17cb5e, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<82> b_a52ea179cbcf660a = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     10, 102, 207, 203, 121, 161,  46, 165,
     21,   0,   0,   0,   1,   0,   1,   0,
    213, 186, 173, 219, 186, 173, 219, 186,
      3,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  10,   1,   0,   0,
     37,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0, 231,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  95, 114,
    117, 110, 116, 105, 109, 101,  46,  99,
     97, 112, 110, 112,  58,  65, 100,  97,
    112, 116, 101, 114,  73, 110, 102, 111,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     16,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     97,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     92,   0,   0,   0,   3,   0,   1,   0,
    104,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101,   0,   0,   0,  82,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,   0,   0,   0,   3,   0,   1,   0,
    112,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    108,   0,   0,   0,   3,   0,   1,   0,
    120,   0,   0,   0,   2,   0,   1,   0,
      3,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   3,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    117,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116,   0,   0,   0,   3,   0,   1,   0,
    128,   0,   0,   0,   2,   0,   1,   0,
    110,  97, 109, 101,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99, 114, 101,  97, 116, 101, 100,  65,
    116,   0,   0,   0,   0,   0,   0,   0,
      9,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      9,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  84, 121,
    112, 101,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    112, 108, 117, 103, 105, 110,  78,  97,
    109, 101,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a52ea179cbcf660a = b_a52ea179cbcf660a.words;
#if !CAPNP_LITE
static const uint16_t m_a52ea179cbcf660a[] = {1, 0, 3, 2};
static const uint16_t i_a52ea179cbcf660a[] = {0, 1, 2, 3};
const ::capnp::_::RawSchema s_a52ea179cbcf660a = {
  0xa52ea179cbcf660a, b_a52ea179cbcf660a.words, 82, nullptr, m_a52ea179cbcf660a,
  0, 4, i_a52ea179cbcf660a, nullptr, nullptr, { &s_a52ea179cbcf660a, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================

namespace rpp {
namespace runtime {

#if !CAPNP_LITE
::capnp::Request< ::rpp::runtime::PluginRuntime::PingParams,  ::rpp::runtime::PluginRuntime::PingResults>
PluginRuntime::Client::pingRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::rpp::runtime::PluginRuntime::PingParams,  ::rpp::runtime::PluginRuntime::PingResults>(
      0xa23e8c8b9e016532ull, 0, sizeHint);
}
::kj::Promise<void> PluginRuntime::Server::ping(PingContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "plugin_runtime.capnp:PluginRuntime", "ping",
      0xa23e8c8b9e016532ull, 0);
}
::capnp::Request< ::rpp::runtime::PluginRuntime::ShutdownParams,  ::rpp::runtime::PluginRuntime::ShutdownResults>
PluginRuntime::Client::shutdownRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::rpp::runtime::PluginRuntime::ShutdownParams,  ::rpp::runtime::PluginRuntime::ShutdownResults>(
      0xa23e8c8b9e016532ull, 1, sizeHint);
}
::kj::Promise<void> PluginRuntime::Server::shutdown(ShutdownContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "plugin_runtime.capnp:PluginRuntime", "shutdown",
      0xa23e8c8b9e016532ull, 1);
}
::capnp::Request< ::rpp::runtime::PluginRuntime::ListAdaptersParams,  ::rpp::runtime::PluginRuntime::ListAdaptersResults>
PluginRuntime::Client::listAdaptersRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::rpp::runtime::PluginRuntime::ListAdaptersParams,  ::rpp::runtime::PluginRuntime::ListAdaptersResults>(
      0xa23e8c8b9e016532ull, 2, sizeHint);
}
::kj::Promise<void> PluginRuntime::Server::listAdapters(ListAdaptersContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "plugin_runtime.capnp:PluginRuntime", "listAdapters",
      0xa23e8c8b9e016532ull, 2);
}
::capnp::Capability::Server::DispatchCallResult PluginRuntime::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (interfaceId) {
    case 0xa23e8c8b9e016532ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("plugin_runtime.capnp:PluginRuntime", interfaceId);
  }
}
::capnp::Capability::Server::DispatchCallResult PluginRuntime::Server::dispatchCallInternal(
    uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        ping(::capnp::Capability::Server::internalGetTypedContext<
             ::rpp::runtime::PluginRuntime::PingParams,  ::rpp::runtime::PluginRuntime::PingResults>(context)),
        false
      };
    case 1:
      return {
        shutdown(::capnp::Capability::Server::internalGetTypedContext<
             ::rpp::runtime::PluginRuntime::ShutdownParams,  ::rpp::runtime::PluginRuntime::ShutdownResults>(context)),
        false
      };
    case 2:
      return {
        listAdapters(::capnp::Capability::Server::internalGetTypedContext<
             ::rpp::runtime::PluginRuntime::ListAdaptersParams,  ::rpp::runtime::PluginRuntime::ListAdaptersResults>(context)),
        false
      };
    default:
      (void)context;
      return ::capnp::Capability::Server::internalUnimplemented(
          "plugin_runtime.capnp:PluginRuntime",
          0xa23e8c8b9e016532ull, methodId);
  }
}
#endif  // !CAPNP_LITE

// PluginRuntime
#if !CAPNP_LITE
constexpr ::capnp::Kind PluginRuntime::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PluginRuntime::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// PluginRuntime::PingParams
constexpr uint16_t PluginRuntime::PingParams::_capnpPrivate::dataWordSize;
constexpr uint16_t PluginRuntime::PingParams::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind PluginRuntime::PingParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PluginRuntime::PingParams::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// PluginRuntime::PingResults
constexpr uint16_t PluginRuntime::PingResults::_capnpPrivate::dataWordSize;
constexpr uint16_t PluginRuntime::PingResults::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind PluginRuntime::PingResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PluginRuntime::PingResults::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// PluginRuntime::ShutdownParams
constexpr uint16_t PluginRuntime::ShutdownParams::_capnpPrivate::dataWordSize;
constexpr uint16_t PluginRuntime::ShutdownParams::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind PluginRuntime::ShutdownParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PluginRuntime::ShutdownParams::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// PluginRuntime::ShutdownResults
constexpr uint16_t PluginRuntime::ShutdownResults::_capnpPrivate::dataWordSize;
constexpr uint16_t PluginRuntime::ShutdownResults::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind PluginRuntime::ShutdownResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PluginRuntime::ShutdownResults::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// PluginRuntime::ListAdaptersParams
constexpr uint16_t PluginRuntime::ListAdaptersParams::_capnpPrivate::dataWordSize;
constexpr uint16_t PluginRuntime::ListAdaptersParams::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind PluginRuntime::ListAdaptersParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PluginRuntime::ListAdaptersParams::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// PluginRuntime::ListAdaptersResults
constexpr uint16_t PluginRuntime::ListAdaptersResults::_capnpPrivate::dataWordSize;
constexpr uint16_t PluginRuntime::ListAdaptersResults::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind PluginRuntime::ListAdaptersResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* PluginRuntime::ListAdaptersResults::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// AdapterInfo
constexpr uint16_t AdapterInfo::_capnpPrivate::dataWordSize;
constexpr uint16_t AdapterInfo::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind AdapterInfo::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* AdapterInfo::_capnpPrivate::schema;
#endif  // !CAPNP_LITE


}  // namespace
}  // namespace

